DROP TABLE IF EXISTS practice2.authors_audios;
DROP TABLE IF EXISTS practice2.audios;
DROP TABLE IF EXISTS practice2.albums;
DROP TABLE IF EXISTS practice2.authors;
DROP TABLE IF EXISTS practice2.groups;
DROP TABLE IF EXISTS practice2.genres;
DROP SCHEMA IF EXISTS practice2;

CREATE SCHEMA IF NOT EXISTS practice2;


CREATE TABLE IF NOT EXISTS practice2.GENRES (
  ID          INT AUTO_INCREMENT PRIMARY KEY,
  GENRE_TITLE VARCHAR(30) NOT NULL,
  UNIQUE (GENRE_TITLE)
);

CREATE TABLE IF NOT EXISTS practice2.GROUPS (
  ID          INT AUTO_INCREMENT PRIMARY KEY,
  GROUP_TITLE VARCHAR(30) NOT NULL,
  UNIQUE (GROUP_TITLE)
);

CREATE TABLE IF NOT EXISTS practice2.ALBUMS (
  ID    INT AUTO_INCREMENT PRIMARY KEY,
  ALBUM_TITLE VARCHAR(60) NOT NULL,
  GENRES_ID   INT,
  UNIQUE (ALBUM_TITLE),
  FOREIGN KEY (GENRES_ID) REFERENCES practice2.GENRES (ID)
);

CREATE TABLE IF NOT EXISTS practice2.AUTHORS (
  ID         INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME TEXT,
  LAST_NAME  TEXT,
  BIRTHDAY   DATE,
  GROUP_ID   INT,
  FOREIGN KEY (GROUP_ID) REFERENCES practice2.GROUPS (ID)
);

CREATE TABLE IF NOT EXISTS practice2.AUDIOS (
  ID       INT AUTO_INCREMENT PRIMARY KEY,
  TITLE    TEXT,
  DURATION INT,
  YEAR     INT,
  ALBUM_ID INT,
  FOREIGN KEY (ALBUM_ID) REFERENCES practice2.ALBUMS (ID)
);

CREATE TABLE IF NOT EXISTS practice2.AUTHORS_AUDIOS (
  AUTHOR_ID INT NOT NULL,
  AUDIO_ID  INT NOT NULL,
  UNIQUE (AUDIO_ID, AUTHOR_ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES practice2.AUTHORS (ID),
  FOREIGN KEY (AUDIO_ID) REFERENCES practice2.AUDIOS (ID)
);